name: Lint and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build --tag fitbot:tests -f Dockerfile.test .
    - name: Lint and unit tests
      run: docker run fitbot:tests